[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "877055b79dda19cf62214a407f0215410aba82d7"
os = "macos"

    [[libwebp.download]]
    sha256 = "959f73f5d69ce5255b9b0c58ae779293824e64e12552c41f3fa5b9857979ae10"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.aarch64-apple-darwin.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "fe463531b386192b5f2b247b063fc81b5768eb38"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "3fde80ca027e685b4cf58a66bcf31484241323dec22235d2195f14eafa0d91f4"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.aarch64-linux-gnu.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "6ccddbe6885bdac58569bf9f74c2b55d890e90d8"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "f9e177ade37a6c8712cdd7de0e3af3f9dd19e40ad999686751966d862be66502"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.aarch64-linux-musl.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "c9e496023acb23289eeeb789fa8fda303a84c1d2"
os = "freebsd"

    [[libwebp.download]]
    sha256 = "38615d29609eb0ee8fe150c3e5066cdc9973554d8effef37f9c392882f55da27"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.aarch64-unknown-freebsd.tar.gz"
[[libwebp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bebb2910de2a470a1e4fcf003e604c9110214b21"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "853b61cd7b34f1656942bf88d5ab710396d9ed8a6aefca45f9650a6b78163b61"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.armv6l-linux-gnueabihf.tar.gz"
[[libwebp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "486768c048074f955c6afa686b4e49e986aca524"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "8afb12389eff8bcabccdf3791f42e14e8a26fff9096b8327d579266870b45633"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.armv6l-linux-musleabihf.tar.gz"
[[libwebp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2424e8861844b3739ef5d0ef0202f4cbe6417d15"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "9b58151264c5b2f55d5d50e951be55d768213816224e9af8fa561e3988019503"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.armv7l-linux-gnueabihf.tar.gz"
[[libwebp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4674d65a5562bd630fe075dc3a2d966030fedf2"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "691ac0cfc76a9a4f0477224f7bdd0df67182c5c9d02fcdee21435dade19cec48"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.armv7l-linux-musleabihf.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "ead87d2ee913bed9f850b5d8b4f8d42ec8a76d70"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "c0d218e940734909bf6f209605e03e287f06cfc9bfb5b2e4559cb70e29d3c002"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.i686-linux-gnu.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "570e0fc764cdf531e87ecf7cacbd3ed889a8e28b"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "f398acf968b88c370c319e4e00e76736c2675e5f4c303b7d1b05a05ae5f3d0c4"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.i686-linux-musl.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "0f0c3ca8e6e0683bce2b4b4d1c496219b2286dca"
os = "windows"

    [[libwebp.download]]
    sha256 = "c940eb52efc34be068877a2e8fa73275ef685d7270ee747827af3f552c19029c"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.i686-w64-mingw32.tar.gz"
[[libwebp]]
arch = "powerpc64le"
git-tree-sha1 = "3af3f76bb6411847e1ab980a271ab845c6827d31"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "12170ec6de6266cbe055a4406984a24c0146575b42fd8dbf6f7643def339fa65"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.powerpc64le-linux-gnu.tar.gz"
[[libwebp]]
arch = "riscv64"
git-tree-sha1 = "f225693426c5fe1ef45e784962853bc4189620a3"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "cab6fc9e55b122dd128c567f1f6c1c4fc99d487bf882339dd3f2400a6faf91f2"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.riscv64-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "d2dd912f0705e2242600912d4c2b76ea10590383"
os = "macos"

    [[libwebp.download]]
    sha256 = "b28fc2ad18154095b0c25f91f97093a23c485cd02f5f829f9075e3c1aa78eea4"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.x86_64-apple-darwin.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "5bef430c2b1432ba97e82bc55d22db0a46175e37"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "fe31b4edc7e26b15f8f06203bea2a95aa52e0c09ad84f609e13f9db49b4d7163"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.x86_64-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "fe1ee875318d3d65677927954e9f903b33b3ea8f"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "212f438366632657ce4fdd7469d6e6fab68d4966ad4eb89a4d19e9cdbe4df3ea"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.x86_64-linux-musl.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "8397ce108254e3b2f3589b33974f4735641c9a2d"
os = "freebsd"

    [[libwebp.download]]
    sha256 = "09cce2329e3554dae499931859de945f2fb5bdc97e23e04027e7f6688d6deba2"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.x86_64-unknown-freebsd.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "4b9e61d49935096732e3b8ebf783a69ecac4300b"
os = "windows"

    [[libwebp.download]]
    sha256 = "153a26fa96d97a4c3972fb0b6bc842ba5323066a6a8628ca14b96418ee7fdbd4"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.5.0+0/libwebp.v1.5.0.x86_64-w64-mingw32.tar.gz"
