[[libwebp]]
arch = "armv7l"
git-tree-sha1 = "2ee85fcbbd1af043bc386f12750651b85f3d0afc"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "76a827784e5ada85b4307401a344a2e0c750e0b47c0e0285839887c6fe4117c0"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.arm-linux-musleabihf.tar.gz"
[[libwebp]]
arch = "powerpc64le"
git-tree-sha1 = "2d4555369c7b839215eba9b18e080ee6fb7ae7a6"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "d2df6eb547ad516c4584de76e2470703e34c98a27d3421a3711a95887e880a20"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.powerpc64le-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "3817b3297006e7229a5a5a45f7037db7d7c503c1"
os = "macos"

    [[libwebp.download]]
    sha256 = "25a20f7a8b36158ba4617f45b6bf57f29a4d574eb66a87a3506cc09d7ea54e80"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.x86_64-apple-darwin14.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "9c571f3e075c8f79bc3e879b4d3e8d1746317aa4"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "abec50bd99b0648d3467d71c5fb73145157e5c57181acf5788a71f2f9e984aad"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.aarch64-linux-gnu.tar.gz"
[[libwebp]]
arch = "armv7l"
git-tree-sha1 = "7f9f8830652d7789d8059beeb298b8afb3bf2633"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "de939d2027ff6d749d1ccfe05d3969df7afc0aa2e4d468fa0c1a3523d18b64b6"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.arm-linux-gnueabihf.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "6aac34c3763441c918c4f39e7e413c23f46f5140"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "d4c4d8467f51ef7e4e5de4845c776f34cf6189f9c5a30121103e177647244887"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.i686-linux-musl.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "523d431a9892f00c37e2d7c79cc1a35a0f869ad1"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "f99d17e5e2eac60ff6db4b5dd5d2d654415b804f887a3be342e7853fa3f86f78"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.x86_64-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "cb5601db9bc66636fd2e2fa51d531fd33107863e"
os = "windows"

    [[libwebp.download]]
    sha256 = "980a6cd81831d5b73324c680e486bb63572a0ff5dff216983988a2a130369ff2"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.x86_64-w64-mingw32.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "9020d8d69c619889ac0db53f8a6c4c788475c6b1"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "371a2a543ece68eddcd4ffc4291686f37cf9d0d6799abd591c8f03c82af38931"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.aarch64-linux-musl.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "bfe324eab33855f1486bb570c3d8f36f8c94ad7d"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "7dc3db53083ad4167c9585499176f10ec05d4874c985edc295e623e1506a22fc"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.i686-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "eacfdbca1d2f55b32bc8d9ebc1e6c5209b83c37e"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "3eedd3042622a2655004816559d643f1c70d1f87ed803584556f28630a37b549"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.x86_64-linux-musl.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "20b2e040a3dad3fface74815a1ebfaaa4177230d"
os = "freebsd"

    [[libwebp.download]]
    sha256 = "0217d99e503b2d0c20183c8ba3e689bf98c34cc84eb759321dda409bc285b1f0"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.x86_64-unknown-freebsd11.1.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "188d04635b85fd2cecc26740639ad25efcceba93"
os = "windows"

    [[libwebp.download]]
    sha256 = "4dcc2e6ae7013ffd74214ff49a8d966ba6cb969824e7ebb78ad8f75e94e019f2"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.0.3+0/libwebp.v1.0.3.i686-w64-mingw32.tar.gz"
