[[libwebp]]
arch = "i686"
git-tree-sha1 = "a22b51d8791b30a1046839bcb7ec5ebb2bd84461"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "4f65fe80c2d0fb9c4761fda073dcda21295884745f2c551ce80501588327cfc7"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.i686-linux-musl.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "93ff46ce7e8e0ff067399ba74a48f77e6ef2ddee"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "08ae7846c84e622b4a93b207f9c34af643df03fc566c6695f4a8bd270bbda2a9"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.aarch64-linux-musl.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "1a54e04e4bc625b5cf22908e94706c3fd8b976e5"
os = "windows"

    [[libwebp.download]]
    sha256 = "ebcb3cd50b1e9289585e28fc5f4e83d19bf5436f71512f9a6c97ffae428d3f6f"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.i686-w64-mingw32.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "90cbfd92ebcd05904623753b6b1e5cb29bbbb12d"
os = "windows"

    [[libwebp.download]]
    sha256 = "2b025f2ded36cb2fed4e33af40e96be4d76972792c6ee1f801eb791be681710d"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.x86_64-w64-mingw32.tar.gz"
[[libwebp]]
arch = "armv7l"
git-tree-sha1 = "6bfcaf59e9a519cc0299425a9c0ddc88f1f7efdb"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "6ca1c7d6165c6b20700229589fed4b56512198737a0b293e3a3de10b397ba22b"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.armv7l-linux-gnueabihf.tar.gz"
[[libwebp]]
arch = "armv7l"
git-tree-sha1 = "b4aae8717c6278d3c23bfcbebf93d1c99e8c808b"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "26cad9d99fdd5d5510c81b794b3b7c7f078af8ed82655f4cb40ec512b37cfceb"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.armv7l-linux-musleabihf.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "d77211382909d3872a5776c645d4c1740c74b5d4"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "7d86360988dcb4290635f5251af142b8da847c0049207ffdce1e23b03f548b19"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.i686-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "6005afed373f49f98c499f35ebd871c875772532"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "9335f67277ea117556d29f18b4c1e27b6ba1aa8ad8061904149a0faffb5e4fb5"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.x86_64-linux-gnu.tar.gz"
[[libwebp]]
arch = "powerpc64le"
git-tree-sha1 = "2ba006438ef60762542bfcf31e44f062f96b5f3f"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "53c8b7191ef1b41bcf2da2d2979493c8ce810831552667e15683ecd8315c9ca4"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.powerpc64le-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "653b60282951aca673a46538221b9d4c510be559"
os = "macos"

    [[libwebp.download]]
    sha256 = "676960d2caad71a5eeccccde656e322abf28548104a2d652ea3486b3bf769ebe"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.x86_64-apple-darwin14.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "1e6f89fb6fb7dd2231b4c5a65ee17c86bba3b4ed"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "806d242132507649d097f5740c13dca264e3d3e303cb5270dcac744931173407"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.aarch64-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "790a64469ab079dd6bc2df01bc9f97e5d46dde7c"
os = "freebsd"

    [[libwebp.download]]
    sha256 = "f1f7c26eaf960bf232f02eefa6b9e54a2ac972d1b32610b60f51b52c54fc3090"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.x86_64-unknown-freebsd11.1.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "9e2f78e3b6d6affee2ef4f120e4b4e7011d1ee6e"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "f67ad09daa19bfe0ed64952957575ff6ccc9ee8b68c70d82d1062bdcecdd0517"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.1.0+0/libwebp.v1.1.0.x86_64-linux-musl.tar.gz"
