[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "8e3db4272f01f6b218fa9d990a5c780e4f1a01e4"
os = "macos"

    [[libwebp.download]]
    sha256 = "d5e17caa6425ff235a435fa6ba9180f094085fcad4be6cc3144b6b8125032075"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.aarch64-apple-darwin.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "7d563fed50b82acb95128823e42e4cdf13d84623"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "022820a0c895d9179b2d1bef1891d86d7944972468bb51f43a2d18179dfafd3e"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.aarch64-linux-gnu.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "0c3e94ea0e93d3dff32436f5d72d7fd25822930c"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "fe080a7446aa68e488993b16e4fc5b13abd509ce9495fd0961bf3cb35e20e54c"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.aarch64-linux-musl.tar.gz"
[[libwebp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "91ff377ba3fdcea5ecc0922cb453c0547778cb84"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "049a9d0a5a74d4920b8696eb17798f072a09facc58617eda1a7006f3a3de0cd5"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.armv6l-linux-gnueabihf.tar.gz"
[[libwebp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9d544d190b6df0cd215e1d75230be9566e3e7586"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "e57362c76e3aeae354711f0b92514dafa95dba1cb3b6083460fbb69d20109c88"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.armv6l-linux-musleabihf.tar.gz"
[[libwebp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54a68bc4804941eaf5cfb613b558bd1c9ada9190"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "22dd8c97e2fd27051816ed6d3a7e992002668e9de7895af228baddc04944ee69"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.armv7l-linux-gnueabihf.tar.gz"
[[libwebp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6f0892c5a4bf79051ceebe7c21a534727fa7c497"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "08b18c3aa9969b6b3805ac094fd744b4b812f459541071b4fdf6e46d78826480"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.armv7l-linux-musleabihf.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "2255188c897dce5570e155b7b2646afefb833fc0"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "c804338e84cf3bfa393c9cb1ba58b2c16e5781e7fde5bfd1c939015bfdcb6ada"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.i686-linux-gnu.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "3c4a756af9ff230c55909068e88b6bc26d4ecd6f"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "d769649b41de69381faeb7b2feb83a679c1ad57d9bc022a28568bcc0b9499d30"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.i686-linux-musl.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "b2023a458d7e269d1a4f136e489461e0a4c8412c"
os = "windows"

    [[libwebp.download]]
    sha256 = "263046609117ffdd76ae77b0eb621d23ea7d5cf80ca42d7e715a8f6eb4599bfc"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.i686-w64-mingw32.tar.gz"
[[libwebp]]
arch = "powerpc64le"
git-tree-sha1 = "fe7777e7d6868ecfe575f36890059cd856bdd591"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "68be58f9afae871e42b60901b1553f8084dc81c101df5737cda6a6c9de6af88c"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.powerpc64le-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "544ae632bc02717508c5e9f98c6a89c0e2c0bb7b"
os = "macos"

    [[libwebp.download]]
    sha256 = "9cce6aed6deb9c2c12a20e8efe40d9c02c39be8a303bce4b456bef97703e139b"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.x86_64-apple-darwin.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "5725549b305400c3def315cd77d918703dbbcf00"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "37cc6da4ca1c1912f26124fde845c4df7d73275e3556f4043c319fd5debb813d"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.x86_64-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "e30714b66eee0bfcd30e24b6e165682bf9d790df"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "1d3ac18e1077e4829f4534d4508ff248edc45445732b4b66e072b6d3ca610ee5"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.x86_64-linux-musl.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "e7abd57a12935a4ac3a2a3b9fa9019723b0f36d6"
os = "freebsd"

    [[libwebp.download]]
    sha256 = "c8d63a25e1ced1ceb2e2b017edf3e9a0162b80a4f932105e7dcfa307bd0c9ae2"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.x86_64-unknown-freebsd.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "f548925e40bd710a2285133ee23303c7f15975ca"
os = "windows"

    [[libwebp.download]]
    sha256 = "c4fabe50cf73c411904b2188c4c38124adc160bc70538c44f346de88787c1ed3"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.4.0+0/libwebp.v1.4.0.x86_64-w64-mingw32.tar.gz"
