[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "cc6d6409838582ae6212fe53f3ebb9c0ea61de91"
os = "macos"

    [[libwebp.download]]
    sha256 = "5fc6bae28c2fdae6284ceaf47436667104ffdb800cd550fafac52bd7cb8302fd"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.aarch64-apple-darwin.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "d3db75cb0f1783c71f56e1ef078d7eec53a5f4c3"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "f904c708e0392d09cb448baf134937d2a62929e11bcddc8207031362f25368a0"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.aarch64-linux-gnu.tar.gz"
[[libwebp]]
arch = "aarch64"
git-tree-sha1 = "0b509f9dd3f7cf5dbc3e981cb617fdc09152fc67"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "363e40bdd2d1f047683529fe58d1a98246d59b8bc7079e72a961b117685e8493"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.aarch64-linux-musl.tar.gz"
[[libwebp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "94633cfb325585bf3b7a2cb624cc1ab1da981214"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "b6e98e147e8566817aa736fb8c22e6f069434bdabbf0fb4674d831a6ef193418"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.armv6l-linux-gnueabihf.tar.gz"
[[libwebp]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "80b65c739ccc709ececc2009f03d16d5e0b6e629"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "d80c2f6dfa8da89713217c62035f22f0647131dff69111630ec646a8a94d5c29"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.armv6l-linux-musleabihf.tar.gz"
[[libwebp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56488c6d6f61c018f31c5d34859ea08ddc9dbdd5"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "b261373e6e5dd1848ad245e0604bbd5e5e7ddbbec6a256aaf4c0adcfe558bf31"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.armv7l-linux-gnueabihf.tar.gz"
[[libwebp]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4292813a40756debf1727dd35bab18d8cb81a161"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "de1492f79a5d24f8abe9c2452432aca309db78b32e2eb2e6cc49e43df4f168c7"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.armv7l-linux-musleabihf.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "c7171225df0592c01a4e91f2468b6d341bba3b13"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "703d9ae29f4a533233f3656ec8c357949a50dcb2dc322e4f0a7df00f4c203b25"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.i686-linux-gnu.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "4ac6467564f2036f7df21fa1a3fb1a0558777bb1"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "2f91de12a74b4e7267877345639c99afa76a784d4fd8c468515b0cf552a49ac6"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.i686-linux-musl.tar.gz"
[[libwebp]]
arch = "i686"
git-tree-sha1 = "21bb6cc0ee10d8e310cfc040e6bbcefda2356d61"
os = "windows"

    [[libwebp.download]]
    sha256 = "6ec2e1ba1a6b029ae6dc66290987379005c31936d56335496edc783eb6df5b66"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.i686-w64-mingw32.tar.gz"
[[libwebp]]
arch = "powerpc64le"
git-tree-sha1 = "291524e14889f674e2973e4b437e2844edb4f615"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "cfa3e8d23a3d1b8959dc8a8c1f2c874d692a3dad3d6a46197cc4ac66d746911a"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.powerpc64le-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "38350fab6cce5b9803dbb38e9e8c49c9200f4bd4"
os = "macos"

    [[libwebp.download]]
    sha256 = "ffbc3be2407da6bb776f611b39ece118279dcf21e7102a62d29cbe5831335705"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.x86_64-apple-darwin.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "97adf1a12e4130e4892950c0618f935972c0baec"
libc = "glibc"
os = "linux"

    [[libwebp.download]]
    sha256 = "ba7270d45d8abcb06b487b99ddcd89fd322cf154084fd7adaec356bbeb1a81ed"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.x86_64-linux-gnu.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "4d669212c280ef1108a010a5ca4affb3c093521b"
libc = "musl"
os = "linux"

    [[libwebp.download]]
    sha256 = "f71699ad7c0728ac66ad98a4d31bdb5d4d1e5f69fbced4acd286d4422768b1ea"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.x86_64-linux-musl.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "4b901313dad413bf3c0c4ec0239f91182d763c07"
os = "freebsd"

    [[libwebp.download]]
    sha256 = "19d9bfaa6e67a99bdcbd1020e140c829626a3b824d46aa63801b812a000a0125"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.x86_64-unknown-freebsd.tar.gz"
[[libwebp]]
arch = "x86_64"
git-tree-sha1 = "7e23ab299e55905610a31959c908661cacb82bcd"
os = "windows"

    [[libwebp.download]]
    sha256 = "86a4cb1c5a8758457e8440523eff4bc1880f193ee8683cdfdbe4a07170c74384"
    url = "https://github.com/JuliaBinaryWrappers/libwebp_jll.jl/releases/download/libwebp-v1.2.4+0/libwebp.v1.2.4.x86_64-w64-mingw32.tar.gz"
